version: "3.7"
services:
  dev_server:
    container_name: music-stuff-dev-server
    build:
        context: ./server
        dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    command: "npm start"
    environment:
      - REDIRECT_URL=http://localhost:8080/auth/callback
      - SPOTIFY_CLIENT_ID="${SPOTIFY_CLIENT_SECRET}"
      - SPOTIFY_CLIENT_SECRET="${SPOTIFY_CLIENT_SECRET}"
      - PORT=3000
    volumes:
      - './server:/app'
      - '/app/node_modules'
  dev_client:
    container_name: music-stuff-dev-client
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    ports:
      - '8080:8080'
    command: "npm run serve"
    environment: 
      - VUE_APP_API_URL=http://localhost:3000/api
    volumes:
      - './client:/app'
      - '/app/node_modules'