version: "3.7"
services:
  server:
    container_name: music-stuff-prod-server
    image: index.docker.io/ropuente/release-radar-server:latest
    environment:
      - REDIRECT_URL="${REDIRECT_URL}"
      - SPOTIFY_CLIENT_ID="${SPOTIFY_CLIENT_SECRET}"
      - SPOTIFY_CLIENT_SECRET="${SPOTIFY_CLIENT_SECRET}"
      - PORT="${PORT}"
    ports:
      - "3000:3000"
    command: "npm run serve"
    env_file:
      - .env
  client:
    container_name: music-stuff-prod-client
    image: index.docker.io/ropuente/release-radar-client:latest
    ports:
      - '8080:80'