version: "3.7"
services:
  server:
    container_name: music-stuff-prod-server
    image: index.docker.io/ropuente/release-radar-server:latest
    build:
        context: ./server
        dockerfile: prod.Dockerfile
    ports:
      - "3000:3000"
    command: "npm run serve"
    env_file:
      - .env
  client:
    container_name: music-stuff-prod-client
    image: index.docker.io/ropuente/release-radar-client:latest
    build:
      context: ./client
      dockerfile: prod.Dockerfile
    env_file:
      - .env
    ports:
      - '8080:80'