name: Build Containers for Prod & Push to Dockerhub

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-deploy-server:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v2
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./server/prod.Dockerfile
        push: true
        tags: ro-puente/release-radar-server:latest
        build-args: |
          PORT=${{ secrets.PORT }}
          REDIRECT_URL=${{ secrets.REDIRECT_URL }}
          SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

  build-and-deploy-client:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v2
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./client/prod.Dockerfile
        push: true
        tags: ro-puente/release-radar-client:latest
        build-args: |
          VUE_APP_API_URL=${{ secrets.VUE_APP_API_URL }}
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}